---
- name: for installing mysql
  hosts: db
  tasks:
    - name: installing required package
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - mysql-server
        - python3
    
    - name: install sql dependencies
      command: 'sudo pip3 install pymysql'


    - name: start the service
      service:
         name: mysqld
         state: started
         enabled: yes
      ignore_errors: yes

    - name: Ensure default user is present.
      mysql_user:
        name: "{{ mysql_user_name }}"
        host: '%'
        password: "{{ mysql_user_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
      when: mysql_user_name != mysql_root_username

    - name: Disallow root login remotely
      command: 'mysql -NBe "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: false

    - name: Update MySQL root password for localhost root account (5.7.x).
      shell: >
        mysql -u root -NBe
        'ALTER USER "{{ mysql_root_username }}"@"localhost"
        IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}"; FLUSH PRIVILEGES;'

